# Default Active Profile: h2 (or switch to 'supabase' to connect to your Supabase instance)
spring.profiles.active=h2

# Common configurations
spring.main.banner-mode=off
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
